# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0

compiler:
  evm_version: null
  solc:
      remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      version: 0.8.15
      optimizer:
          enabled: true
          runs: 200
  vyper:
      version: null
